package generator

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"

	"github.com/smtdfc/dix/parser"
)

type Generator struct{}

func NewGenerator() *Generator {
	return &Generator{}
}

func (g *Generator) GenerateDep(dep *parser.Dependency, scope *Scope) (ast.Expr, error) {
	if dep.IsSingleton {
		ident, ok := scope.Names[dep.Type.Signature()]
		if !ok {
			return nil, fmt.Errorf("Dependency not found: %s", dep.Name)
		}

		return ident, nil
	}

	return nil, nil
}

func (g *Generator) GenerateCallComposition(composition *parser.Composition, scope *Scope) (ast.Expr, error) {
	deps := []ast.Expr{}

	for _, dep := range composition.Deps {
		depIdent, err := g.GenerateDep(dep, scope)
		if err != nil {
			return nil, err
		}

		deps = append(deps, depIdent)
	}

	provider := scope.Import(composition.PackagePath)
	expr := &ast.CallExpr{
		Fun: &ast.SelectorExpr{
			X:   provider,
			Sel: ast.NewIdent(composition.Name),
		},
		Args: deps,
	}

	return expr, nil
}

func (g *Generator) GenerateImportStmt(scope *Scope) (*ast.GenDecl, error) {

	specs := []ast.Spec{}

	for path, ident := range scope.Imports {
		specs = append(specs, &ast.ImportSpec{
			Name: ident,
			Path: &ast.BasicLit{
				Value: fmt.Sprintf("%q", path),
				Kind:  token.STRING,
			},
		})
	}

	return &ast.GenDecl{
		Tok:    token.IMPORT,
		Lparen: token.Pos(1),
		Specs:  specs,
	}, nil
}

func (g *Generator) GenerateCreateObjectStmt(ident *ast.Ident, composition *parser.Composition, scope *Scope) (ast.Stmt, error) {
	deps := []ast.Expr{}

	for _, dep := range composition.Deps {
		depIdent, err := g.GenerateDep(dep, scope)
		if err != nil {
			return nil, err
		}

		deps = append(deps, depIdent)
	}

	callExpr, err := g.GenerateCallComposition(composition, scope)
	if err != nil {
		return nil, err
	}

	stmt := &ast.AssignStmt{
		Lhs: []ast.Expr{
			ident,
		},
		Tok: token.DEFINE,

		Rhs: []ast.Expr{callExpr},
	}

	return stmt, nil

}

func (g *Generator) Generate(metadata *parser.Metadata) (string, error) {
	var compositionMap = CompositionMap{}
	scope := NewScope()

	if metadata.Root == nil {
		return "", errors.New("Cannot find composition root")
	}

	for _, composition := range metadata.Compositions {
		compositionMap[composition.Return.Type.Signature()] = composition
	}

	graph, err := BuildGraph(metadata.Root, compositionMap)
	if err != nil {
		return "", err
	}

	sortedCompositions := graph.Sort()

	fset := token.NewFileSet()

	file := &ast.File{
		Name: ast.NewIdent("generated"),
	}

	// file.Doc = &ast.CommentGroup{
	// 	List: []*ast.Comment{
	// 		{Text: "//go:build !dix"},
	// 		{Text: "// +build !dix"},
	// 		{Text: "// Code generated by dix. DO NOT EDIT."},
	// 		{Text: "//dix:ignore"},
	// 	},
	// }

	stmts := []ast.Stmt{}

	for _, composition := range sortedCompositions {
		id := scope.UniqueIdent(composition.Return.Type.Name)
		stmt, err := g.GenerateCreateObjectStmt(id, composition, scope)
		if err != nil {
			return "", err
		}
		stmts = append(stmts, stmt)
	}

	fn := &ast.FuncDecl{
		Name: ast.NewIdent("Root"),
		Type: &ast.FuncType{Params: &ast.FieldList{}},
		Body: &ast.BlockStmt{
			List: stmts,
		},
	}

	importDecls, err := g.GenerateImportStmt(scope)
	if err != nil {
		return "", err
	}

	file.Decls = []ast.Decl{importDecls, fn}

	var buf bytes.Buffer

	if err := format.Node(&buf, fset, file); err != nil {
		return "", err
	}

	return buf.String(), nil
}
